{
 "title": "Node Exporter Server Metrics - Custom",
 "description": "Dashboard to view multiple servers",
 "tags": [ "prometheus" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(node_boot_time{job!=\"prometheus\"}, instance)"
   },
   {
    "name": "port",
    "label": "port",
    "query": "label_values(node_boot_time, instance)"
   }
  ]
 },
 "panels": [
  { "title": "$node", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 }, "repeat": "node" },
  { "title": "$node", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 12, "y": 0 } },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 1 },
   "repeat": "node",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(node_cpu{instance=~\"$node:$port\", mode=\"system\"}>0.0000001)"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(node_cpu{instance=~\"$node:$port\", mode=\"system\"}>0.0000001)"
    }
   ]
  },
  {
   "title": "CPU Busy (Avg)",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 3 },
   "repeat": "node",
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(((count(count(node_cpu{instance=~\"$node:$port\"}>0.000001) by (cpu))) - avg(sum by (mode)(irate(node_cpu{mode='idle',instance=~\"$node:$port\"}[5m])))) * 100) / count(count(node_cpu{instance=~\"$node:$port\"}>0.000001) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU Busy (Avg)",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 3 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(((count(count(node_cpu{instance=~\"$node:$port\"}>0.000001) by (cpu))) - avg(sum by (mode)(irate(node_cpu{mode='idle',instance=~\"$node:$port\"}[5m])))) * 100) / count(count(node_cpu{instance=~\"$node:$port\"}>0.000001) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "repeat": "node",
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "sum by (mode)(irate(node_cpu{mode=\"system\",instance=~'$node:$port'}[5m]))",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='user',instance=~'$node:$port'}[5m]))",
     "legendFormat": "user"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='nice',instance=~'$node:$port'}[5m]))",
     "legendFormat": "nice"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='iowait',instance=~'$node:$port'}[5m]))",
     "legendFormat": "iowait"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='steal',instance=~'$node:$port'}[5m]))",
     "legendFormat": "steal"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='idle',instance=~'$node:$port'}[5m]))",
     "legendFormat": "idle"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='irq',instance=~'$node:$port'}[5m]))",
     "legendFormat": "irq"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='softirq',instance=~'$node:$port'}[5m]))",
     "legendFormat": "softirq"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='guest',instance=~'$node:$port'}[5m]))",
     "legendFormat": "guest"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "sum by (mode)(irate(node_cpu{mode=\"system\",instance=~'$node:$port'}[5m]))",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='user',instance=~'$node:$port'}[5m]))",
     "legendFormat": "user"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='nice',instance=~'$node:$port'}[5m]))",
     "legendFormat": "nice"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='iowait',instance=~'$node:$port'}[5m]))",
     "legendFormat": "iowait"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='steal',instance=~'$node:$port'}[5m]))",
     "legendFormat": "steal"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='idle',instance=~'$node:$port'}[5m]))",
     "legendFormat": "idle"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='irq',instance=~'$node:$port'}[5m]))",
     "legendFormat": "irq"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='softirq',instance=~'$node:$port'}[5m]))",
     "legendFormat": "softirq"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu{mode='guest',instance=~'$node:$port'}[5m]))",
     "legendFormat": "guest"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "repeat": "node",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(node_cpu{instance=~\"$node:$port\", mode=\"system\"}>0.0000001)",
     "legendFormat": "Nb Cores"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(node_cpu{instance=~\"$node:$port\", mode=\"system\"}>0.0000001)",
     "legendFormat": "Nb Cores"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "repeat": "node",
   "yaxes": [
    { "format": "bytes", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "( node_memory_MemTotal{instance=~'$node:$port'} - node_memory_MemFree{instance=~'$node:$port'} - node_memory_Buffers{instance=~'$node:$port'} - node_memory_Cached{instance=~'$node:$port'} - node_memory_SwapCached{instance=~'$node:$port'} - node_memory_Slab{instance=~'$node:$port'} - node_memory_PageTables{instance=~'$node:$port'} - node_memory_VmallocUsed{instance=~'$node:$port'} )",
     "legendFormat": "Apps"
    },
    {
     "expr": "node_memory_Buffers{instance=~'$node:$port'}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached{instance=~'$node:$port'}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree{instance=~'$node:$port'}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_Slab{instance=~'$node:$port'}",
     "legendFormat": "Slab"
    },
    {
     "expr": "node_memory_SwapCached{instance=~'$node:$port'}",
     "legendFormat": "SwapCached"
    },
    {
     "expr": "node_memory_PageTables{instance=~'$node:$port'}",
     "legendFormat": "PageTables"
    },
    {
     "expr": "node_memory_VmallocUsed{instance=~'$node:$port'}",
     "legendFormat": "VmallocUsed"
    },
    {
     "expr": "(node_memory_SwapTotal{instance=~'$node:$port'} - node_memory_SwapFree{instance=~'$node:$port'})",
     "legendFormat": "Swap"
    },
    {
     "expr": "node_memory_Committed_AS{instance=~'$node:$port'}",
     "legendFormat": "Committed"
    },
    {
     "expr": "node_memory_Mapped{instance=~'$node:$port'}",
     "legendFormat": "Mapped"
    },
    {
     "expr": "node_memory_Active{instance=~'$node:$port'}",
     "legendFormat": "Active"
    },
    {
     "expr": "node_memory_Inactive{instance=~'$node:$port'}",
     "legendFormat": "Inactive"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "( node_memory_MemTotal{instance=~'$node:$port'} - node_memory_MemFree{instance=~'$node:$port'} - node_memory_Buffers{instance=~'$node:$port'} - node_memory_Cached{instance=~'$node:$port'} - node_memory_SwapCached{instance=~'$node:$port'} - node_memory_Slab{instance=~'$node:$port'} - node_memory_PageTables{instance=~'$node:$port'} - node_memory_VmallocUsed{instance=~'$node:$port'} )",
     "legendFormat": "Apps"
    },
    {
     "expr": "node_memory_Buffers{instance=~'$node:$port'}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached{instance=~'$node:$port'}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree{instance=~'$node:$port'}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_Slab{instance=~'$node:$port'}",
     "legendFormat": "Slab"
    },
    {
     "expr": "node_memory_SwapCached{instance=~'$node:$port'}",
     "legendFormat": "SwapCached"
    },
    {
     "expr": "node_memory_PageTables{instance=~'$node:$port'}",
     "legendFormat": "PageTables"
    },
    {
     "expr": "node_memory_VmallocUsed{instance=~'$node:$port'}",
     "legendFormat": "VmallocUsed"
    },
    {
     "expr": "(node_memory_SwapTotal{instance=~'$node:$port'} - node_memory_SwapFree{instance=~'$node:$port'})",
     "legendFormat": "Swap"
    },
    {
     "expr": "node_memory_Committed_AS{instance=~'$node:$port'}",
     "legendFormat": "Committed"
    },
    {
     "expr": "node_memory_Mapped{instance=~'$node:$port'}",
     "legendFormat": "Mapped"
    },
    {
     "expr": "node_memory_Active{instance=~'$node:$port'}",
     "legendFormat": "Active"
    },
    {
     "expr": "node_memory_Inactive{instance=~'$node:$port'}",
     "legendFormat": "Inactive"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node:$port\"}",
     "legendFormat": "load"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node:$port\"}",
     "legendFormat": "load"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "repeat": "node",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100.0 - 100 * (node_filesystem_avail{instance=~'$node:$port',device !~'tmpfs',device!~'by-uuid'} / node_filesystem_size{instance=~'$node:$port',device !~'tmpfs',device!~'by-uuid'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100.0 - 100 * (node_filesystem_avail{instance=~'$node:$port',device !~'tmpfs',device!~'by-uuid'} / node_filesystem_size{instance=~'$node:$port',device !~'tmpfs',device!~'by-uuid'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk Utilization per Device",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "repeat": "node",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_ms{instance=~\"$node:$port\",device=~\"dm-.+\"}[5m])/10",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Utilization per Device",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_ms{instance=~\"$node:$port\",device=~\"dm-.+\"}[5m])/10",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk IOs per Device",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "repeat": "node",
   "yaxes": [
    { "format": "short", "label": "IO/second read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed{instance=~'$node:$port',device=~\"dm-.+\"}[5m])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_writes_completed{instance=~'$node:$port',device=~\"dm-.+\"}[5m])",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "Disk IOs per Device",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short", "label": "IO/second read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed{instance=~'$node:$port',device=~\"dm-.+\"}[5m])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_writes_completed{instance=~'$node:$port',device=~\"dm-.+\"}[5m])",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "Disk Throughput per Device",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "repeat": "node",
   "yaxes": [
    {
     "format": "bytes",
     "label": "Bytes/second read (-) / write (+)"
    }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_sectors_read{instance=~'$node:$port',device=~\"dm-.+\"}[5m]) * 512",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_sectors_written{instance=~'$node:$port',device=~\"dm-.+\"}[5m]) * 512",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "Disk Throughput per Device",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    {
     "format": "bytes",
     "label": "Bytes/second read (-) / write (+)"
    }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_sectors_read{instance=~'$node:$port',device=~\"dm-.+\"}[5m]) * 512",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_sectors_written{instance=~'$node:$port',device=~\"dm-.+\"}[5m]) * 512",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_context_switches{instance=~\"$node:$port\"}[5m])",
     "legendFormat": "context switches"
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_context_switches{instance=~\"$node:$port\"}[5m])",
     "legendFormat": "context switches"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 70 },
   "repeat": "node",
   "yaxes": [
    { "format": "bits", "label": "bits in (-) / bits out (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes{instance=~'$node:$port'}[5m])*8",
     "legendFormat": "{{device}}_in"
    },
    {
     "expr": "irate(node_network_transmit_bytes{instance=~'$node:$port'}[5m])*8",
     "legendFormat": "{{device}}_out"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "bits", "label": "bits in (-) / bits out (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes{instance=~'$node:$port'}[5m])*8",
     "legendFormat": "{{device}}_in"
    },
    {
     "expr": "irate(node_network_transmit_bytes{instance=~'$node:$port'}[5m])*8",
     "legendFormat": "{{device}}_out"
    }
   ]
  },
  {
   "title": "Netstat",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 77 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~'$node:$port'}",
     "legendFormat": "established"
    }
   ]
  },
  {
   "title": "Netstat",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~'$node:$port'}",
     "legendFormat": "established"
    }
   ]
  },
  {
   "title": "UDP Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 84 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Udp_InDatagrams{instance=~\"$node:$port\"}[5m])",
     "legendFormat": "Udp_InDatagrams"
    },
    {
     "expr": "irate(node_netstat_Udp_InErrors{instance=~\"$node:$port\"}[5m])",
     "legendFormat": "Udp_InErrors"
    },
    {
     "expr": "irate(node_netstat_Udp_OutDatagrams{instance=~\"$node:$port\"}[5m])",
     "legendFormat": "Udp_OutDatagrams"
    },
    {
     "expr": "irate(node_netstat_Udp_NoPorts{instance=~\"$node:$port\"}[5m])",
     "legendFormat": "Udp_NoPorts"
    }
   ]
  },
  {
   "title": "UDP Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_netstat_Udp_InDatagrams{instance=~\"$node:$port\"}[5m])",
     "legendFormat": "Udp_InDatagrams"
    },
    {
     "expr": "irate(node_netstat_Udp_InErrors{instance=~\"$node:$port\"}[5m])",
     "legendFormat": "Udp_InErrors"
    },
    {
     "expr": "irate(node_netstat_Udp_OutDatagrams{instance=~\"$node:$port\"}[5m])",
     "legendFormat": "Udp_OutDatagrams"
    },
    {
     "expr": "irate(node_netstat_Udp_NoPorts{instance=~\"$node:$port\"}[5m])",
     "legendFormat": "Udp_NoPorts"
    }
   ]
  }
 ]
}